-- Create table for storing Push Subscriptions
create table if not exists public.push_subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade default auth.uid(),
    endpoint text not null unique,
    keys jsonb not null,
    user_agent text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.push_subscriptions enable row level security;

-- Policies
create policy "Users can insert their own subscriptions"
on public.push_subscriptions for insert
with check (auth.uid() = user_id);

create policy "Users can delete their own subscriptions"
on public.push_subscriptions for delete
using (auth.uid() = user_id);

create policy "Users can view their own subscriptions"
on public.push_subscriptions for select
using (auth.uid() = user_id);

-- Start fresh if needed (Optional: careful with this in production)
-- truncate table public.push_subscriptions;
