-- Create the blocked_dates table
create table if not exists public.blocked_dates (
  id bigint generated by default as identity primary key,
  blocked_date date not null unique,
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security) if you want to restrict access, 
-- but for now, if you want it openly readable by authenticated users:
alter table public.blocked_dates enable row level security;

-- Policy: Everyone can read
create policy "Enable read access for all users" 
on public.blocked_dates for select 
using (true);

-- Policy: Only authenticated (or specific logic) can insert/update/delete.
-- For simplicity in this project phase, you might allow anon read and authenticated write
create policy "Enable insert for authenticated users only" 
on public.blocked_dates for insert 
with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" 
on public.blocked_dates for update 
using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" 
on public.blocked_dates for delete 
using (auth.role() = 'authenticated');
