-- Add columns to profiles
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS nickname text,
ADD COLUMN IF NOT EXISTS birth_day int,
ADD COLUMN IF NOT EXISTS birth_month int,
ADD COLUMN IF NOT EXISTS gender text, -- 'Male', 'Female', 'Not Specified'
ADD COLUMN IF NOT EXISTS line_uid text,
ADD COLUMN IF NOT EXISTS admin_notes text;

-- Add columns to menu_items
ALTER TABLE menu_items 
ADD COLUMN IF NOT EXISTS is_pickup_available boolean DEFAULT true;

-- Create store_exceptions table
CREATE TABLE IF NOT EXISTS store_exceptions (
    id bigint generated by default as identity primary key,
    date date not null,
    is_closed boolean default true,
    reason text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure menu_categories has display_order if not exists (it likely does based on context, but good to ensure)
ALTER TABLE menu_categories 
ADD COLUMN IF NOT EXISTS display_order int DEFAULT 0;
