import { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

// คำแปลภาษา
const translations = {
    th: {
        // Header
        welcome: 'ยินดีต้อนรับ',
        login: 'เข้าสู่ระบบ',
        logout: 'ออกจากระบบ',
        guest: 'ผู้เยี่ยมชม',

        // Home
        headline: 'haus table.',
        subHeadline: 'by ร้านในบ้าน in the haus',
        description: 'ระบบจองโต๊ะและมารับอาหารที่ร้าน',
        dineIn: 'จองโต๊ะ (Dine-in)',
        takeaway: 'สั่งกลับบ้าน (Pickup)',
        bookTable: 'จองโต๊ะ',
        orderPickup: 'สั่งอาหาร',
        openNow: 'เปิดให้บริการ',
        loginGoogle: 'เข้าสู่ระบบด้วย Google',

        // Booking & Pickup
        backToHome: 'กลับหน้าหลัก',
        back: 'ย้อนกลับ',
        step1: 'เลือกเมนู',
        step2: 'สรุปยอด',
        addToCart: 'ใส่ตะกร้า',
        added: 'เพิ่มแล้ว',
        cartTotal: 'ยอดรวม',
        confirmOrder: 'ยืนยันการสั่งซื้อ',
        yourName: 'ชื่อผู้รับ',
        phoneNumber: 'เบอร์โทรศัพท์',
        pickupTime: 'เวลารับสินค้า',
        paymentTitle: 'ชำระเงิน',
        uploadSlip: 'แนบสลิป',
        agreement: 'ยอมรับเงื่อนไข',
        disclaimer: 'หากไม่มารับภายใน 1 ชม. 30 นาที และติดต่อไม่ได้ ทางร้านขอสงวนสิทธิ์ยกเลิกออเดอร์และไม่คืนเงินทุกกรณี',
        minOrderWarn: 'ขั้นต่ำ 180 บาท',
        reservation: 'จองโต๊ะ',
        stepDate: 'ขั้นตอน 1/3',
        stepSeat: 'ขั้นตอน 2/3',
        stepFood: 'ขั้นตอน 3/3',
        selectSeat: 'เลือกที่นั่ง',
        foodAndDetail: 'อาหาร & รายละเอียด',
        confirmBooking: 'ยืนยันการจอง',
        date: 'วันที่',
        timeSlot: 'เวลารับบริการ',
        guests: 'จำนวนลูกค้า',
        selectTable: 'เลือกโต๊ะนี้',
        orderFood: 'สั่งอาหาร',
        searchMenu: 'ค้นหาเมนู...',
        next: 'ถัดไป',
        skipFood: 'ข้ามขั้นตอนอาหาร',
        bookingDetail: 'รายละเอียดการจอง',
        foodTotal: 'ค่าอาหาร',
        paymentRequired: 'จำเป็นต้องชำระเงิน',
        uploadSlipDesc: 'กรุณาแนบสลิปเพื่อยืนยันการจอง',
        agreeTerms: 'ฉันยอมรับเงื่อนไข',
        processing: 'กำลังดำเนินการ...',
        shopClosed: 'ร้านปิดอยู่',
        openUntil: 'เปิดถึง',
        opensAt: 'เปิดเวลา',
        selected: 'เลือกแล้ว',
        available: 'ว่าง',
        pleaseTapTable: 'กรุณาเลือกโต๊ะ',
        table: 'โต๊ะ',
        minCondition: 'หากไม่มารับภายใน 90 นาที ออเดอร์จะถูกยกเลิก',

        // Auth
        welcomeBack: 'ยินดีต้อนรับกลับ',
        createAccount: 'สร้างบัญชีใหม่',
        loginDesc: 'เข้าสู่ระบบเพื่อสั่งอาหาร',
        joinDesc: 'สมัครสมาชิกเพื่อสั่งจองได้สะดวกรวดเร็ว',
        emailAddr: 'อีเมล',
        password: 'รหัสผ่าน',
        passwordConfirm: 'ยืนยันรหัสผ่าน',
        humanCheck: 'ยืนยันตัวตน: ผลบวกของ',
        dontHaveAcc: 'ยังไม่มีบัญชี?',
        signUp: 'สมัครสมาชิก',
        alreadyHave: 'มีบัญชีอยู่แล้ว?',
        loginBtn: 'เข้าสู่ระบบ',
        accountReady: 'สมัครสมาชิกเรียบร้อย',
        readyDesc: 'หลังลงทะเบียนคุณสามารถใช้งานได้ทันที',
        verifyEmail: 'กรุณายืนยันอีเมล',
        emailSentTo: 'ระบบได้ส่งลิงก์ยืนยันไปที่',
        checkInbox: 'โปรดตรวจสอบกล่องจดหมายเพื่อเปิดใช้งานบัญชี',
        backToLogin: 'กลับไปหน้าเข้าสู่ระบบ',
        continueGoogle: 'ดำเนินการต่อด้วย Google',
        orEmail: 'หรือ อีเมล',

        // Admin
        adminDashboard: 'จัดการการจอง',
        status: 'สถานะ',
        approve: 'อนุมัติ',
        reject: 'ยกเลิก',
        // Tracking Page
        trackingTitle: 'ติดตามสถานะ',
        orderReceived: 'ได้รับออเดอร์แล้ว',
        bookingReceived: 'ได้รับจองแล้ว',
        orderCancelled: 'รายการถูกยกเลิก',
        orderSuccess: 'สั่งอาหารสำเร็จ!',
        bookingSuccess: 'จองโต๊ะสำเร็จ!',
        contactShop: 'กรุณาติดต่อร้านค้าเพื่อสอบถามข้อมูลเพิ่มเติม',
        thankYouService: 'ขอบคุณที่ใช้บริการครับ',
        yourShortId: 'รหัสออเดอร์ (Short ID)',
        trackingLink: 'ลิงก์ติดตามสถานะ',
        copyLink: 'คัดลอกลิงก์',
        keepLinkWarning: 'โปรดเก็บลิงก์นี้ไว้ เพื่อใช้ตรวจสอบสถานะอาหารและคิวของคุณ',
        cancelledWarning: 'รายการนี้ถูกยกเลิก โปรดติดต่อร้านค้าหากมีข้อสงสัย',
        bookingInfo: 'ข้อมูลการจอง',
        tableNumber: 'หมายเลขโต๊ะ',
        dateDate: 'วันที่',
        dateTime: 'เวลา',
        orderItems: 'รายการอาหาร',
        totalPrice: 'ยอดรวม',
        callShop: 'โทรติดต่อร้าน',
        lineChat: 'แชทไลน์ (LINE)',
        sendToLine: 'ส่งเข้า LINE',
        addToCalendar: 'ลงปฏิทิน',
        saveSlip: 'บันทึกใบรับออเดอร์',
        saving: 'กำลังบันทึก...',
        slipNotePickup: '*บันทึกได้เมื่ออาหารเสร็จแล้ว',
        slipNoteBooking: '*บันทึกได้เมื่อยืนยันโต๊ะแล้ว',
        statusLatest: 'สถานะล่าสุด',
        statusCancelledBody: 'ขออภัย รายการนี้ถูกยกเลิก\nโปรดติดต่อเจ้าหน้าที่',
        mapGoogle: 'แผนที่ร้าน',
        callButton: 'โทรหาเรา',
        
        // Tracking Steps
        stepPending: 'รอพนักงานยืนยัน',
        stepConfirmed: 'จองโต๊ะสำเร็จ',
        stepSeated: 'เช็คอินแล้ว',
        stepCompleted: 'เสร็จสิ้น',
        
        stepPickupPending: 'รอรับออเดอร์',
        stepPickupConfirmed: 'กำลังเตรียม',
        stepPickupPreparing: 'กำลังปรุงอาหาร',
        stepPickupReady: 'พร้อมรับออเดอร์',
        stepPickupCompleted: 'รับสินค้าแล้ว',

        // Booking Components
        bookingSummary: 'สรุปการจอง',
        dateUnavailable: 'วันดังกล่าวปิดให้บริการ',
        selectDateFirst: '(กรุณาเลือกวันที่ก่อน)',
        largeGroupTitle: 'จองโต๊ะมากกว่า 10 ท่าน',
        largeGroupDesc: 'สำหรับหมู่คณะมากกว่า 10 ท่าน กรุณาติดต่อทางร้านโดยตรงเพื่อจัดเตรียมที่นั่งพิเศษ',
        call: 'โทร',
        close: 'ปิด',
        clickToEnlarge: 'คลิกเพื่อขยาย',
        noQrCode: 'ไม่มี QR Code',
        changeFile: 'เปลี่ยนรูป',
        tapToUpload: 'กดเพื่ออัปโหลด',
        condition: 'เงื่อนไข',
        minSpendError: 'ยอดขั้นต่ำต่อท่านคือ',
        pleaseOrderMore: 'กรุณาสั่งอาหารเพิ่มอีก',
        noMenuItems: 'ไม่พบรายการอาหาร',
        itemsCount: 'รายการ',
        payOnly: 'ข้ามไปชำระเงิน',
        full: 'เต็ม',
        seats: 'ที่นั่ง',
        select: 'เลือก',
        bookedTooltip: 'ไม่ว่าง',
        
        // Pickup Specific
        contactInfo: 'ข้อมูลติดต่อ',
        orderSummary: 'สรุปรายการ',
        checkout: 'ชำระเงิน',
        pickup: 'รับสินค้าเอง',
        today: 'วันนี้',
        tomorrow: 'พรุ่งนี้',
        specialRequest: 'คำขอพิเศษ (Note)',
        specialRequestPlaceholder: 'แพ้อาหาร, เพิ่มเติม...',
        noValidTimes: 'ไม่มีรอบเวลาว่าง',
        advanceBooking: 'จองล่วงหน้าอย่างน้อย',
        hours: 'ชั่วโมง',
        note: 'หมายเหตุ',
        total: 'รวมทั้งหมด',
        fillContact: 'กรุณากรอกข้อมูลติดต่อ',
        selectPickupTime: 'เลือกเวลารับสินค้า',
    },
    en: {
        // Header
        welcome: 'Welcome',
        login: 'Login',
        logout: 'Logout',
        guest: 'Guest',

        // Home
        headline: 'haus table.',
        subHeadline: 'by In The Haus',
        description: 'Table booking & Pickup ordering system',
        dineIn: 'Dine-in',
        takeaway: 'Takeaway',
        bookTable: 'Book Table',
        orderPickup: 'Order Pickup',
        openNow: 'Open Now',
        loginGoogle: 'Login with Google',

        // Booking & Pickup
        backToHome: 'Back to Home',
        back: 'Back',
        step1: 'Menu',
        step2: 'Summary',
        addToCart: 'Add',
        added: 'Added',
        cartTotal: 'Total',
        confirmOrder: 'Confirm Order',
        yourName: 'Your Name',
        phoneNumber: 'Phone Number',
        pickupTime: 'Pickup Time',
        paymentTitle: 'Payment',
        uploadSlip: 'Upload Slip',
        agreement: 'Accept Terms',
        disclaimer: 'If not picked up within 1.5 hours and unreachable, the order will be cancelled with NO REFUND.',
        minOrderWarn: 'Min order 180 THB',
        reservation: 'Reservation',
        stepDate: 'Step 1/3',
        stepSeat: 'Step 2/3',
        stepFood: 'Step 3/3',
        selectSeat: 'Select Seat',
        foodAndDetail: 'Food & Detail',
        confirmBooking: 'Confirm Booking',
        date: 'Date',
        timeSlot: 'Time Slot',
        guests: 'Guests',
        selectTable: 'Select Table',
        orderFood: 'Order Food',
        searchMenu: 'Search menu...',
        next: 'Next',
        skipFood: 'Skip Food & Continue',
        bookingDetail: 'Booking Detail',
        foodTotal: 'Food Total',
        paymentRequired: 'Payment Required',
        uploadSlipDesc: 'Please upload a slip to confirm your booking.',
        agreeTerms: 'I agree to terms',
        processing: 'Processing...',
        shopClosed: 'Shop is currently closed',
        openUntil: 'Open until',
        opensAt: 'Opens at',
        selected: 'Selected',
        available: 'Available',
        pleaseTapTable: 'Please tap a table',
        table: 'Table',
        minCondition: 'Order will be cancelled without refund if not picked up within 90 minutes.',

        // Auth
        welcomeBack: 'Welcome Back',
        createAccount: 'Create Account',
        loginDesc: 'Login to continue ordering',
        joinDesc: 'Join us to order faster',
        emailAddr: 'Email Address',
        password: 'Password',
        passwordConfirm: 'Confirm Password',
        humanCheck: 'Human Check: What is',
        dontHaveAcc: "Don't have an account?",
        signUp: 'Sign up',
        alreadyHave: 'Already have an account?',
        loginBtn: 'Log in',
        accountReady: 'Account Ready',
        readyDesc: 'You can use your account immediately.',
        verifyEmail: 'Verify Your Email',
        emailSentTo: "We've sent a confirmation link to",
        checkInbox: 'Please check your inbox (and spam) to activate your account.',
        backToLogin: 'Back to Login',
        continueGoogle: 'Continue with Google',
        orEmail: 'OR EMAIL',

        // Admin
        adminDashboard: 'Admin Dashboard',
        status: 'Status',
        approve: 'Approve',
        reject: 'Reject',

        // Tracking Page
        trackingTitle: 'Tracking',
        orderReceived: 'Order Received',
        bookingReceived: 'Booking Received',
        orderCancelled: 'Order Cancelled',
        orderSuccess: 'Order Successful!',
        bookingSuccess: 'Booking Successful!',
        contactShop: 'Please contact the shop for more info.',
        thankYouService: 'Thank you for your service.',
        yourShortId: 'Order ID (Short)',
        trackingLink: 'Tracking Link',
        copyLink: 'Copy',
        keepLinkWarning: 'Please keep this link to check your status.',
        cancelledWarning: 'This order is cancelled. Contact us if you have questions.',
        bookingInfo: 'Booking Info',
        tableNumber: 'Table',
        dateDate: 'Date',
        dateTime: 'Time',
        orderItems: 'Order Items',
        totalPrice: 'Total',
        callShop: 'Call Shop',
        lineChat: 'LINE Chat',
        sendToLine: 'Send to LINE',
        addToCalendar: 'Calendar',
        saveSlip: 'Save Slip',
        saving: 'Saving...',
        slipNotePickup: '*Available when ready',
        slipNoteBooking: '*Available when confirmed',
        statusLatest: 'Latest Status',
        statusCancelledBody: 'Sorry, this order is cancelled.\nPlease contact staff.',
        mapGoogle: 'Google Maps',
        callButton: 'Call Us',

        // Tracking Steps
        stepPending: 'Waiting Confirmation',
        stepConfirmed: 'Booking Confirmed',
        stepSeated: 'Seated',
        stepCompleted: 'Completed',
        
        stepPickupPending: 'Order Sent',
        stepPickupConfirmed: 'Preparing',
        stepPickupPreparing: 'Cooking',
        stepPickupReady: 'Ready for Pickup',
        stepPickupCompleted: 'Collected',

        // Booking Components
        bookingSummary: 'Booking Summary',
        dateUnavailable: 'The selected date is unavailable',
        selectDateFirst: '(Please select date first)',
        largeGroupTitle: 'Bookings Over 10 People',
        largeGroupDesc: 'For groups over 10, please contact us directly for special arrangements.',
        call: 'Call',
        close: 'Close',
        clickToEnlarge: 'Click to Enlarge',
        noQrCode: 'No QR Code',
        changeFile: 'Change',
        tapToUpload: 'Tap to Upload',
        condition: 'Condition',
        minSpendError: 'Minimum spend per person is',
        pleaseOrderMore: 'Please add more items worth',
        noMenuItems: 'No menu items found',
        itemsCount: 'Items',
        payOnly: 'Skip Food (Pay Only)',
        full: 'Full',
        seats: 'Seats',
        select: 'Select',
        bookedTooltip: 'Booked',

        // Pickup Specific
        contactInfo: 'Contact Info',
        orderSummary: 'Order Summary',
        checkout: 'Checkout',
        pickup: 'Pickup',
        today: 'Today',
        tomorrow: 'Tomorrow',
        specialRequest: 'Special Request (Note)',
        specialRequestPlaceholder: 'Allergies, additional details...',
        noValidTimes: 'No valid times available',
        advanceBooking: 'Advance booking minimum',
        hours: 'hours',
        note: 'Note',
        total: 'Total',
        fillContact: 'Please fill contact info',
        selectPickupTime: 'Select pickup time',
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('th');

    const toggleLanguage = () => {
        setLang(prev => prev === 'th' ? 'en' : 'th');
    };

    const t = (key) => translations[lang][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
