-- Create a table for global store settings
CREATE TABLE IF NOT EXISTS public.store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_food_cost_pct NUMERIC DEFAULT 30.0, -- Default target 30%
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Insert default row if not exists (Singleton pattern)
INSERT INTO public.store_settings (id, target_food_cost_pct)
SELECT 1, 30.0
WHERE NOT EXISTS (SELECT 1 FROM public.store_settings WHERE id = 1);

-- RLS Policies (Open for now for ease of use, restrict later if needed)
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.store_settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated update" ON public.store_settings FOR UPDATE USING (auth.role() = 'authenticated');
