-- ==============================================================================
-- Migration: Enable Row Level Security (RLS) on store_exceptions & promotion_codes
-- Purpose: Resolve Supabase Security Advisor Critical warnings ("RLS Disabled in Public")
-- Date: 2026-09-04
-- ==============================================================================

-- 1. Ensure tables exist before enabling RLS
CREATE TABLE IF NOT EXISTS public.store_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    is_closed BOOLEAN DEFAULT true,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.promotion_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
    discount_value NUMERIC NOT NULL CHECK (discount_value > 0),
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    applicable_to TEXT NOT NULL CHECK (applicable_to IN ('booking', 'ordering', 'both')),
    min_spend NUMERIC NOT NULL DEFAULT 0 CHECK (min_spend >= 0),
    is_active BOOLEAN NOT NULL DEFAULT true,
    usage_limit INT,
    used_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.store_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_codes ENABLE ROW LEVEL SECURITY;

-- 3. Policies for public.store_exceptions
DROP POLICY IF EXISTS "store_exceptions_read" ON public.store_exceptions;
DROP POLICY IF EXISTS "Allow public read access on store_exceptions" ON public.store_exceptions;
CREATE POLICY "store_exceptions_read" ON public.store_exceptions
    FOR SELECT TO anon, authenticated
    USING (true);

DROP POLICY IF EXISTS "store_exceptions_write" ON public.store_exceptions;
DROP POLICY IF EXISTS "Allow full access to store_exceptions" ON public.store_exceptions;
CREATE POLICY "store_exceptions_write" ON public.store_exceptions
    FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);

GRANT ALL ON public.store_exceptions TO anon, authenticated, service_role;

-- 4. Policies for public.promotion_codes
DROP POLICY IF EXISTS "promotion_codes_read" ON public.promotion_codes;
DROP POLICY IF EXISTS "Allow public read access on promotion_codes" ON public.promotion_codes;
CREATE POLICY "promotion_codes_read" ON public.promotion_codes
    FOR SELECT TO anon, authenticated
    USING (true);

DROP POLICY IF EXISTS "promotion_codes_write" ON public.promotion_codes;
DROP POLICY IF EXISTS "Allow full access to promotion_codes" ON public.promotion_codes;
CREATE POLICY "promotion_codes_write" ON public.promotion_codes
    FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);

GRANT ALL ON public.promotion_codes TO anon, authenticated, service_role;

-- 5. Force PostgREST schema reload
NOTIFY pgrst, 'reload schema';
